[tool.poetry]
name = "sql-research-assistant"
version = "0.0.1"
description = "Uses GPT Researcher as a research agent over SQL"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.0,<3.12"
langchain = "^0.1"
openai = ">=1.10.0,<2.0.0"
bs4 = "^0.0.1"
duckduckgo-search = "^4.1.0"
tavily-python = "^0.3.1"
tiktoken = "^0.5.2"
pyodbc = "5.1.0"
azure-storage-blob = "^12.19.0"
azure-ai-formrecognizer = "^3.3.2"
langchain-experimental = "^0.0.51"
pypdf = "^4.0.1"
docx2txt = "^0.8"
unstructured = "^0.12.4"
openpyxl = "^3.1.2"
networkx = "^3.2.1"
pydantic = "<2.0"
langchain-openai = "^0.0.6"
langchain-community = "^0.0.20"


[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"
fastapi = "^0.104.0"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "sql_research_assistant"
export_attr = "chain"

[tool.templates-hub]
use-case = "research"
author = "LangChain"
integrations = ["Ollama", "OpenAI"]
tags = ["data", "agents", "sql", "local-models"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
